server:
  servlet:
    context-path: /api

spring:
  # 多环境配置
  profiles:
    active: dev
  datasource:
    # JDBC 连接相关配置（其它配置参见多环境配置）
    username: root
    password: 123456
    # 数据库连接池相关配置
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: RealEstateSalesManageSystem
      max-lifetime: 60000
      connection-timeout: 30000
  redis:
    # Redis 连接相关配置
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB

mybatis-plus:
  global-config:
    db-config:
      # 主键类型默认设置为自动递增
      id-type: AUTO

image:
  path: uploads

---
# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    # 开发环境下使用 p6spy 执行 SQL 分析打印
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/real-estate-sales-ms
---
# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    # 使用 p6spy 会有性能损耗，因此在生产环境中使用 MySQL 驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/real-estate-sales-ms